# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-11 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newblog', '0002_blogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='emailid',
            field=models.CharField(default='spam@gmail.com', max_length=100),
        ),
    ]
