# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-11 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newblog', '0003_blogs_emailid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='emailid',
            field=models.CharField(max_length=100),
        ),
    ]
