# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-19 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newblog', '0005_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogid', models.IntegerField()),
                ('emailid', models.CharField(max_length=100, unique=True)),
                ('comments', models.TextField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
