# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-19 19:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newblog', '0006_auto_20180419_1906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomments',
            old_name='comments',
            new_name='comt',
        ),
    ]
