# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-19 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newblog', '0007_auto_20180419_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomments',
            name='emailid',
            field=models.CharField(max_length=100),
        ),
    ]
